import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))

import check  # noqa: E402


class RepoFixture:
    """Builds a throwaway repository tree for one test."""

    def __init__(self):
        self._dir = tempfile.TemporaryDirectory()
        self.root = Path(self._dir.name)

    def write(self, relative: str, content: str) -> Path:
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return path

    def cleanup(self):
        self._dir.cleanup()


class CheckTestCase(unittest.TestCase):
    def setUp(self):
        self.repo = RepoFixture()
        self.addCleanup(self.repo.cleanup)


class DocsParityTest(CheckTestCase):
    def test_reports_pages_missing_in_either_language(self):
        self.repo.write("docs/en/index.md", "# Index\n")
        self.repo.write("docs/en/install.md", "# Install\n")
        self.repo.write("docs/fr/index.md", "# Index\n")
        self.repo.write("docs/fr/extra.md", "# Extra\n")
        problems = check.check_docs_parity(self.repo.root)
        self.assertEqual(
            problems,
            ["docs/fr/install.md is missing (exists in docs/en)", "docs/en/extra.md is missing (exists in docs/fr)"],
        )

    def test_passes_when_trees_match(self):
        self.repo.write("docs/en/a/b.md", "x")
        self.repo.write("docs/fr/a/b.md", "x")
        self.assertEqual(check.check_docs_parity(self.repo.root), [])


class LinksTest(CheckTestCase):
    def test_reports_broken_files_and_anchors(self):
        self.repo.write("docs/en/target.md", "# Real Heading\n\n## Second `code` part\n")
        self.repo.write(
            "docs/en/index.md",
            "[ok](target.md#real-heading) [ok2](target.md#second-code-part) [web](https://example.com)\n"
            "[bad](missing.md) [badanchor](target.md#nope) [self](#local)\n\n## Local\n",
        )
        problems = check.check_links(self.repo.root)
        self.assertEqual(len(problems), 2, problems)
        self.assertIn("broken link to 'missing.md'", problems[0])
        self.assertIn("missing anchor '#nope'", problems[1])

    def test_ignores_links_inside_code_fences(self):
        self.repo.write("README.md", "```\n[x](nowhere.md)\n```\n")
        self.assertEqual(check.check_links(self.repo.root), [])

    def test_duplicate_headings_get_numbered_anchors(self):
        self.assertEqual(check.heading_anchors("# A\n## A\n"), {"a", "a-1"})


class PublicWordingTest(CheckTestCase):
    def test_flags_internal_references(self):
        self.repo.write("docs/en/index.md", "See the roadmap.md for plans.\nThis page was generated by AI.\n")
        problems = check.check_public_wording(self.repo.root)
        self.assertEqual(len(problems), 2, problems)

    def test_allows_normal_prose(self):
        self.repo.write("docs/en/index.md", "Install the package and restart the server.\n")
        self.assertEqual(check.check_public_wording(self.repo.root), [])


class UnsafeLuaTest(CheckTestCase):
    def test_flags_disabled_functions(self):
        self.repo.write(
            "package/Server/x.lua",
            'io.open("a")\nos.execute("b")\nlocal m = require("c")\nlocal p = package.path\ndofile("d")\n',
        )
        self.assertEqual(len(check.check_unsafe_lua(self.repo.root)), 5)

    def test_allows_engine_equivalents_and_comments(self):
        self.repo.write(
            "package/Server/x.lua",
            'Package.Require("a.lua")\nlocal t = os.clock() + os.time()\n-- io.open is disabled\nlocal s = "io.open"\nlocal r = ratio.value\n',
        )
        self.assertEqual(check.check_unsafe_lua(self.repo.root), [])


class ClientSecretsTest(CheckTestCase):
    def test_flags_credentials_and_database_in_client_visible_files(self):
        self.repo.write("package/Shared/config.lua", 'local password = "hunter2"\n')
        self.repo.write("package/Client/db.lua", 'local db = Database(DatabaseEngine.SQLite, "x")\n')
        problems = check.check_client_secrets(self.repo.root)
        self.assertEqual(len(problems), 3, problems)

    def test_ignores_server_files(self):
        self.repo.write("package/Server/db.lua", 'local db = Database(DatabaseEngine.SQLite, "x")\n')
        self.assertEqual(check.check_client_secrets(self.repo.root), [])


class SecretsTest(CheckTestCase):
    def test_flags_known_secret_formats(self):
        aws_key = "AKIA" + "ABCDEFGHIJKLMNOP"
        github_token = "ghp_" + "a" * 36
        key_header = "-----BEGIN " + "PRIVATE KEY-----"
        self.repo.write("notes.txt", f"{aws_key}\n{github_token}\n{key_header}\n")
        self.assertEqual(len(check.check_secrets(self.repo.root)), 3)

    def test_skips_ignored_directories(self):
        self.repo.write(".tmp/leak.txt", "ghp_" + "b" * 36 + "\n")
        self.assertEqual(check.check_secrets(self.repo.root), [])


class TodoMarkersTest(CheckTestCase):
    def test_flags_markers_in_shipped_code_only(self):
        self.repo.write("package/Server/a.lua", "-- " + "TODO" + " finish\n")
        self.repo.write("tests/unit/a_spec.lua", "-- " + "TODO" + " allowed here\n")
        problems = check.check_todo_markers(self.repo.root)
        self.assertEqual(len(problems), 1)
        self.assertIn("package/Server/a.lua:1", problems[0])


class VersionsTest(CheckTestCase):
    def write_versions(self, manifest: str, module: str, changelog: str | None):
        self.repo.write("package/Package.toml", f'[meta]\n    version = "{manifest}"\n')
        self.repo.write("package/Shared/foundation/version.lua", f'return {{ PRODUCT = "{module}" }}\n')
        if changelog is not None:
            self.repo.write("CHANGELOG.md", changelog)

    def test_passes_when_consistent(self):
        self.write_versions("1.2.3", "1.2.3", "## [Unreleased]\n")
        self.assertEqual(check.check_versions(self.repo.root), [])

    def test_reports_mismatch(self):
        self.write_versions("1.2.3", "1.2.4", "## [Unreleased]\n")
        self.assertIn("version mismatch", check.check_versions(self.repo.root)[0])

    def test_reports_missing_changelog_section(self):
        self.write_versions("1.2.3", "1.2.3", "## [1.0.0]\n")
        self.assertIn("neither an [Unreleased]", check.check_versions(self.repo.root)[0])

    def test_rejects_non_core_semver(self):
        self.write_versions("1.2.3-dev", "1.2.3-dev", "## [Unreleased]\n")
        self.assertIn("is not X.Y.Z", check.check_versions(self.repo.root)[0])


class DocExamplesTest(CheckTestCase):
    def setUp(self):
        super().setUp()
        self.repo.write("tests/example/Index.lua", "local a = 1\nif a then\n\tprint(a)\nend\n")

    def test_accepts_identical_blocks_with_spaces_for_tabs(self):
        self.repo.write(
            "docs/en/page.md",
            "<!-- example: tests/example/Index.lua -->\n```lua\nlocal a = 1\nif a then\n    print(a)\nend\n```\n",
        )
        self.assertEqual(check.check_doc_examples(self.repo.root), [])

    def test_reports_differences_and_missing_sources(self):
        self.repo.write(
            "docs/en/page.md",
            "<!-- example: tests/example/Index.lua -->\n```lua\nlocal a = 2\n```\n"
            "<!-- example: tests/missing.lua -->\n```lua\n```\n"
            "<!-- example: tests/example/Index.lua -->\nno block here\n",
        )
        problems = check.check_doc_examples(self.repo.root)
        self.assertEqual(len(problems), 3, problems)
        self.assertIn("differs from tests/example/Index.lua", problems[0])
        self.assertIn("does not exist", problems[1])
        self.assertIn("not followed by a code block", problems[2])


class RequirePathsTest(CheckTestCase):
    def setUp(self):
        super().setUp()
        self.repo.write("package/Shared/foundation/core/json.lua", "return {}\n")
        self.repo.write("package/Shared/foundation/core/log.lua", "return {}\n")
        self.repo.write("package/Server/foundation/core/audit.lua", "return {}\n")

    def test_accepts_paths_resolved_like_nanos(self):
        self.repo.write(
            "package/Server/foundation/bootstrap.lua",
            'local a = Package.Require("foundation/core/json.lua")\n'
            'local b = Package.Require("foundation/core/audit.lua")\n'
            'local c = Package.Require("core/audit.lua")\n',
        )
        self.repo.write("package/Shared/foundation/core/runtime.lua", 'local l = Package.Require("log.lua")\n')
        self.assertEqual(check.check_require_paths(self.repo.root), [])

    def test_rejects_parent_segments_wrong_case_and_missing_files(self):
        self.repo.write(
            "package/Server/foundation/core/config.lua",
            'local a = Package.Require("../../../Shared/foundation/core/json.lua")\n'
            'local b = Package.Require("foundation/core/JSON.lua")\n'
            'local c = Package.Require("foundation/core/nope.lua")\n',
        )
        problems = check.check_require_paths(self.repo.root)
        self.assertEqual(len(problems), 3, problems)
        self.assertIn("uses '..'", problems[0])
        self.assertIn("different casing", problems[1])
        self.assertIn("does not resolve", problems[2])


class StripLuaCommentsTest(unittest.TestCase):
    def test_keeps_strings_containing_dashes(self):
        self.assertEqual(check.strip_lua_comments('local a = "--x" -- note'), 'local a = "--x" ')

    def test_handles_escaped_quotes(self):
        self.assertEqual(check.strip_lua_comments('local a = "\\"--" -- c'), 'local a = "\\"--" ')

    def test_code_only_blanks_string_contents(self):
        self.assertEqual(check.lua_code_only('f("io.open", \'x\') -- io.'), "f(\"\", '') ")


if __name__ == "__main__":
    unittest.main()
